[project]
name = "load-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
"pyarrow",
"docker",
"loguru",
"psutil",
"gputil",
"pandas",
"datasets",
]